name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [assigned, opened, synchronize, reopened]

jobs:
  build-library-and-examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev libcurl4-openssl-dev uncrustify libyaml-dev
    - name: Build client library
      run: |
        cd kubernetes
        mkdir build
        cd build
        cmake ..
        make
    - name: Build authentication plugin - oidc
      run: |
        cd kubernetes/config/authn_plugin/plugins/oidc
        mkdir build
        cd build
        cmake ..
        make
    - name: Build examples
      run: |
        cd examples/
        make
    - name: Create k8s kind cluster
      uses: helm/kind-action@v1.1.0
    - name: Test examples
      run: |
        cd examples/
        LD_LIBRARY_PATH=$GITHUB_WORKSPACE/kubernetes/build/ make test
